import pytest
from unittest.mock import MagicMock, patch, mock_open
import app.tts.elevenlabs as elevenlabs_module


class TestElevenLabsService:

    @patch("app.tts.elevenlabs.ElevenLabs")
    @patch("app.tts.elevenlabs.os.getenv")
    def test_init_success(self, mock_getenv, mock_elevenlabs_client):
        """Test successful initialization of ElevenLabsService."""
        mock_getenv.side_effect = lambda key: {
            "ELEVENLABS_API_KEY": "test-api-key",
            "ELEVENLABS_VOICE_ID": "test-voice-id",
            "ELEVENLABS_MODEL_ID": "test-model-id",
            "TTS_OUTPUT_FILE": "test_output",
            "TTS_OUTPUT_FORMAT": "mp3"
        }.get(key)

        service = elevenlabs_module.ElevenLabsService()

        mock_elevenlabs_client.assert_called_once_with(api_key="test-api-key")
        assert service.voice_id == "test-voice-id"
        assert service.model_id == "test-model-id"
        assert service.output_file == "test_output"
        assert service.output_format == "mp3"

    @patch("app.tts.elevenlabs.ElevenLabs")
    @patch("app.tts.elevenlabs.os.getenv")
    def test_text_to_speech_calls_api(self, mock_getenv, mock_elevenlabs_client):
        """Test that text_to_speech calls the ElevenLabs API with correct parameters."""
        mock_getenv.side_effect = lambda key: {
            "ELEVENLABS_API_KEY": "test-api-key",
            "ELEVENLABS_VOICE_ID": "test-voice-id",
            "ELEVENLABS_MODEL_ID": "test-model-id",
            "TTS_OUTPUT_FILE": "test_output",
            "TTS_OUTPUT_FORMAT": "mp3"
        }.get(key)

        mock_client_instance = MagicMock()
        mock_elevenlabs_client.return_value = mock_client_instance
        mock_client_instance.text_to_speech.convert.return_value = iter([b"audio", b"data"])

        service = elevenlabs_module.ElevenLabsService()

        with patch("builtins.open", mock_open()) as mocked_file:
            service.text_to_speech("Hello world")

            mock_client_instance.text_to_speech.convert.assert_called_once_with(
                text="Generated by ElevenLabs: Hello world",
                voice_id="test-voice-id",
                model_id="test-model-id",
                output_format="mp3",
            )

    @patch("app.tts.elevenlabs.ElevenLabs")
    @patch("app.tts.elevenlabs.os.getenv")
    def test_text_to_speech_writes_to_file(self, mock_getenv, mock_elevenlabs_client):
        """Test that text_to_speech writes audio bytes to the correct file."""
        mock_getenv.side_effect = lambda key: {
            "ELEVENLABS_API_KEY": "test-api-key",
            "ELEVENLABS_VOICE_ID": "test-voice-id",
            "ELEVENLABS_MODEL_ID": "test-model-id",
            "TTS_OUTPUT_FILE": "test_output",
            "TTS_OUTPUT_FORMAT": "mp3"
        }.get(key)

        mock_client_instance = MagicMock()
        mock_elevenlabs_client.return_value = mock_client_instance
        mock_client_instance.text_to_speech.convert.return_value = iter([b"audio", b"data"])

        service = elevenlabs_module.ElevenLabsService()

        with patch("builtins.open", mock_open()) as mocked_file:
            service.text_to_speech("Hello world")

            mocked_file.assert_called_once_with("test_output.mp3", "wb")
            mocked_file().write.assert_called_once_with(b"audiodata")

    @patch("app.tts.elevenlabs.ElevenLabs")
    @patch("app.tts.elevenlabs.os.getenv")
    def test_text_to_speech_joins_audio_chunks(self, mock_getenv, mock_elevenlabs_client):
        """Test that audio generator chunks are properly joined."""
        mock_getenv.side_effect = lambda key: {
            "ELEVENLABS_API_KEY": "test-api-key",
            "ELEVENLABS_VOICE_ID": "test-voice-id",
            "ELEVENLABS_MODEL_ID": "test-model-id",
            "TTS_OUTPUT_FILE": "test_output",
            "TTS_OUTPUT_FORMAT": "mp3"
        }.get(key)

        mock_client_instance = MagicMock()
        mock_elevenlabs_client.return_value = mock_client_instance
        mock_client_instance.text_to_speech.convert.return_value = iter([b"chunk1", b"chunk2", b"chunk3"])

        service = elevenlabs_module.ElevenLabsService()

        with patch("builtins.open", mock_open()) as mocked_file:
            service.text_to_speech("Test")

            mocked_file().write.assert_called_once_with(b"chunk1chunk2chunk3")


class TestGetElevenLabsService:

    def setup_method(self):
        """Reset the singleton before each test."""
        elevenlabs_module.elevenlabs_service = None

    @patch("app.tts.elevenlabs.ElevenLabs")
    @patch("app.tts.elevenlabs.os.getenv")
    def test_get_elevenlabs_service_creates_instance(self, mock_getenv, mock_elevenlabs_client):
        """Test that get_elevenlabs_service creates a new ElevenLabsService instance."""
        mock_getenv.side_effect = lambda key: {
            "ELEVENLABS_API_KEY": "test-api-key",
            "ELEVENLABS_VOICE_ID": "test-voice-id",
            "ELEVENLABS_MODEL_ID": "test-model-id",
            "TTS_OUTPUT_FILE": "test_output",
            "TTS_OUTPUT_FORMAT": "mp3"
        }.get(key)

        service = elevenlabs_module.get_elevenlabs_service()

        assert service is not None
        assert isinstance(service, elevenlabs_module.ElevenLabsService)

    @patch("app.tts.elevenlabs.ElevenLabs")
    @patch("app.tts.elevenlabs.os.getenv")
    def test_get_elevenlabs_service_returns_singleton(self, mock_getenv, mock_elevenlabs_client):
        """Test that get_elevenlabs_service returns the same instance on subsequent calls."""
        mock_getenv.side_effect = lambda key: {
            "ELEVENLABS_API_KEY": "test-api-key",
            "ELEVENLABS_VOICE_ID": "test-voice-id",
            "ELEVENLABS_MODEL_ID": "test-model-id",
            "TTS_OUTPUT_FILE": "test_output",
            "TTS_OUTPUT_FORMAT": "mp3"
        }.get(key)

        service1 = elevenlabs_module.get_elevenlabs_service()
        service2 = elevenlabs_module.get_elevenlabs_service()

        assert service1 is service2
        mock_elevenlabs_client.assert_called_once()

    @patch("app.tts.elevenlabs.ElevenLabs")
    @patch("app.tts.elevenlabs.os.getenv")
    def test_get_elevenlabs_service_caches_instance(self, mock_getenv, mock_elevenlabs_client):
        """Test that the service is cached in the global variable."""
        mock_getenv.side_effect = lambda key: {
            "ELEVENLABS_API_KEY": "test-api-key",
            "ELEVENLABS_VOICE_ID": "test-voice-id",
            "ELEVENLABS_MODEL_ID": "test-model-id",
            "TTS_OUTPUT_FILE": "test_output",
            "TTS_OUTPUT_FORMAT": "mp3"
        }.get(key)

        assert elevenlabs_module.elevenlabs_service is None

        service = elevenlabs_module.get_elevenlabs_service()

        assert elevenlabs_module.elevenlabs_service is service
