import pytest
from unittest.mock import MagicMock, patch
import app.tts.pytts as pytts_module


class TestPyTTSService:

    @patch("app.tts.pytts.pyttsx3.init")
    @patch("app.tts.pytts.get_settings")
    def test_init_success(self, mock_get_settings, mock_pyttsx3_init):
        """Test successful initialization of PyTTSService."""
        mock_settings = MagicMock()
        mock_settings.pytts_voice_rate = 150
        mock_settings.pytts_volume = 0.9
        mock_settings.pytts_voice_id = "0"
        mock_settings.tts_output_path = "test_output.mp3"
        mock_get_settings.return_value = mock_settings

        mock_engine = MagicMock()
        mock_voice = MagicMock()
        mock_voice.id = "voice-id-0"
        mock_engine.getProperty.return_value = [mock_voice]
        mock_pyttsx3_init.return_value = mock_engine

        service = pytts_module.PyTTSService()

        mock_pyttsx3_init.assert_called_once()
        mock_engine.setProperty.assert_any_call("rate", 150)
        mock_engine.setProperty.assert_any_call("volume", 0.9)
        mock_engine.setProperty.assert_any_call("voice", "voice-id-0")
        assert service.output_path == "test_output.mp3"

    @patch("app.tts.pytts.pyttsx3.init")
    @patch("app.tts.pytts.get_settings")
    def test_text_to_speech_saves_to_file(self, mock_get_settings, mock_pyttsx3_init):
        """Test that text_to_speech saves audio to the correct file."""
        mock_settings = MagicMock()
        mock_settings.pytts_voice_rate = 150
        mock_settings.pytts_volume = 0.9
        mock_settings.pytts_voice_id = "0"
        mock_settings.tts_output_path = "test_output.mp3"
        mock_get_settings.return_value = mock_settings

        mock_engine = MagicMock()
        mock_voice = MagicMock()
        mock_voice.id = "voice-id-0"
        mock_engine.getProperty.return_value = [mock_voice]
        mock_pyttsx3_init.return_value = mock_engine

        service = pytts_module.PyTTSService()
        service.text_to_speech("Hello world")

        mock_engine.save_to_file.assert_called_once_with(
            "Generated by PyTTS: Hello world", "test_output.mp3"
        )

    @patch("app.tts.pytts.pyttsx3.init")
    @patch("app.tts.pytts.get_settings")
    def test_text_to_speech_runs_and_waits(self, mock_get_settings, mock_pyttsx3_init):
        """Test that text_to_speech calls runAndWait and stop."""
        mock_settings = MagicMock()
        mock_settings.pytts_voice_rate = 150
        mock_settings.pytts_volume = 0.9
        mock_settings.pytts_voice_id = "0"
        mock_settings.tts_output_path = "test_output.mp3"
        mock_get_settings.return_value = mock_settings

        mock_engine = MagicMock()
        mock_voice = MagicMock()
        mock_voice.id = "voice-id-0"
        mock_engine.getProperty.return_value = [mock_voice]
        mock_pyttsx3_init.return_value = mock_engine

        service = pytts_module.PyTTSService()
        service.text_to_speech("Test")

        mock_engine.runAndWait.assert_called_once()
        mock_engine.stop.assert_called_once()

    @patch("app.tts.pytts.pyttsx3.init")
    @patch("app.tts.pytts.get_settings")
    def test_init_with_different_voice_id(self, mock_get_settings, mock_pyttsx3_init):
        """Test initialization with a different voice ID."""
        mock_settings = MagicMock()
        mock_settings.pytts_voice_rate = 200
        mock_settings.pytts_volume = 1.0
        mock_settings.pytts_voice_id = "1"
        mock_settings.tts_output_path = "output.mp3"
        mock_get_settings.return_value = mock_settings

        mock_engine = MagicMock()
        mock_voice_0 = MagicMock()
        mock_voice_0.id = "voice-id-0"
        mock_voice_1 = MagicMock()
        mock_voice_1.id = "voice-id-1"
        mock_engine.getProperty.return_value = [mock_voice_0, mock_voice_1]
        mock_pyttsx3_init.return_value = mock_engine

        service = pytts_module.PyTTSService()

        mock_engine.setProperty.assert_any_call("voice", "voice-id-1")


class TestGetPyTTSService:

    def setup_method(self):
        """Reset the singleton before each test."""
        pytts_module.pytts_service = None

    @patch("app.tts.pytts.pyttsx3.init")
    @patch("app.tts.pytts.get_settings")
    def test_get_pytts_service_creates_instance(
        self, mock_get_settings, mock_pyttsx3_init
    ):
        """Test that get_pytts_service creates a new PyTTSService instance."""
        mock_settings = MagicMock()
        mock_settings.pytts_voice_rate = 150
        mock_settings.pytts_volume = 0.9
        mock_settings.pytts_voice_id = "0"
        mock_settings.tts_output_path = "test_output.mp3"
        mock_get_settings.return_value = mock_settings

        mock_engine = MagicMock()
        mock_voice = MagicMock()
        mock_voice.id = "voice-id-0"
        mock_engine.getProperty.return_value = [mock_voice]
        mock_pyttsx3_init.return_value = mock_engine

        service = pytts_module.get_pytts_service()

        assert service is not None
        assert isinstance(service, pytts_module.PyTTSService)

    @patch("app.tts.pytts.pyttsx3.init")
    @patch("app.tts.pytts.get_settings")
    def test_get_pytts_service_returns_singleton(
        self, mock_get_settings, mock_pyttsx3_init
    ):
        """Test that get_pytts_service returns the same instance on subsequent calls."""
        mock_settings = MagicMock()
        mock_settings.pytts_voice_rate = 150
        mock_settings.pytts_volume = 0.9
        mock_settings.pytts_voice_id = "0"
        mock_settings.tts_output_path = "test_output.mp3"
        mock_get_settings.return_value = mock_settings

        mock_engine = MagicMock()
        mock_voice = MagicMock()
        mock_voice.id = "voice-id-0"
        mock_engine.getProperty.return_value = [mock_voice]
        mock_pyttsx3_init.return_value = mock_engine

        service1 = pytts_module.get_pytts_service()
        service2 = pytts_module.get_pytts_service()

        assert service1 is service2
        mock_pyttsx3_init.assert_called_once()

    @patch("app.tts.pytts.pyttsx3.init")
    @patch("app.tts.pytts.get_settings")
    def test_get_pytts_service_caches_instance(
        self, mock_get_settings, mock_pyttsx3_init
    ):
        """Test that the service is cached in the global variable."""
        mock_settings = MagicMock()
        mock_settings.pytts_voice_rate = 150
        mock_settings.pytts_volume = 0.9
        mock_settings.pytts_voice_id = "0"
        mock_settings.tts_output_path = "test_output.mp3"
        mock_get_settings.return_value = mock_settings

        mock_engine = MagicMock()
        mock_voice = MagicMock()
        mock_voice.id = "voice-id-0"
        mock_engine.getProperty.return_value = [mock_voice]
        mock_pyttsx3_init.return_value = mock_engine

        assert pytts_module.pytts_service is None

        service = pytts_module.get_pytts_service()

        assert pytts_module.pytts_service is service
