import pytest
from unittest.mock import MagicMock, patch
import app.tts.pytts as pytts_module


class TestPyTTSService:

    @patch("app.tts.pytts.pyttsx3.init")
    @patch("app.tts.pytts.os.getenv")
    def test_init_success(self, mock_getenv, mock_pyttsx3_init):
        """Test successful initialization of PyTTSService."""
        mock_getenv.side_effect = lambda key: {
            "PYTTS_VOICE_RATE": "150",
            "PYTTS_VOLUME": "0.9",
            "PYTTS_VOICE_ID": "0",
            "TTS_OUTPUT_FILE": "test_output",
            "TTS_OUTPUT_FORMAT": "mp3"
        }.get(key)

        mock_engine = MagicMock()
        mock_voice = MagicMock()
        mock_voice.id = "voice-id-0"
        mock_engine.getProperty.return_value = [mock_voice]
        mock_pyttsx3_init.return_value = mock_engine

        service = pytts_module.PyTTSService()

        mock_pyttsx3_init.assert_called_once()
        mock_engine.setProperty.assert_any_call("rate", 150)
        mock_engine.setProperty.assert_any_call("volume", 0.9)
        mock_engine.setProperty.assert_any_call("voice", "voice-id-0")
        assert service.output_file == "test_output"
        assert service.output_format == "mp3"

    @patch("app.tts.pytts.pyttsx3.init")
    @patch("app.tts.pytts.os.getenv")
    def test_text_to_speech_saves_to_file(self, mock_getenv, mock_pyttsx3_init):
        """Test that text_to_speech saves audio to the correct file."""
        mock_getenv.side_effect = lambda key: {
            "PYTTS_VOICE_RATE": "150",
            "PYTTS_VOLUME": "0.9",
            "PYTTS_VOICE_ID": "0",
            "TTS_OUTPUT_FILE": "test_output",
            "TTS_OUTPUT_FORMAT": "mp3"
        }.get(key)

        mock_engine = MagicMock()
        mock_voice = MagicMock()
        mock_voice.id = "voice-id-0"
        mock_engine.getProperty.return_value = [mock_voice]
        mock_pyttsx3_init.return_value = mock_engine

        service = pytts_module.PyTTSService()
        service.text_to_speech("Hello world")

        mock_engine.save_to_file.assert_called_once_with(
            "Generated by PyTTS: Hello world",
            "test_output.mp3"
        )

    @patch("app.tts.pytts.pyttsx3.init")
    @patch("app.tts.pytts.os.getenv")
    def test_text_to_speech_runs_and_waits(self, mock_getenv, mock_pyttsx3_init):
        """Test that text_to_speech calls runAndWait and stop."""
        mock_getenv.side_effect = lambda key: {
            "PYTTS_VOICE_RATE": "150",
            "PYTTS_VOLUME": "0.9",
            "PYTTS_VOICE_ID": "0",
            "TTS_OUTPUT_FILE": "test_output",
            "TTS_OUTPUT_FORMAT": "mp3"
        }.get(key)

        mock_engine = MagicMock()
        mock_voice = MagicMock()
        mock_voice.id = "voice-id-0"
        mock_engine.getProperty.return_value = [mock_voice]
        mock_pyttsx3_init.return_value = mock_engine

        service = pytts_module.PyTTSService()
        service.text_to_speech("Test")

        mock_engine.runAndWait.assert_called_once()
        mock_engine.stop.assert_called_once()

    @patch("app.tts.pytts.pyttsx3.init")
    @patch("app.tts.pytts.os.getenv")
    def test_init_with_different_voice_id(self, mock_getenv, mock_pyttsx3_init):
        """Test initialization with a different voice ID."""
        mock_getenv.side_effect = lambda key: {
            "PYTTS_VOICE_RATE": "200",
            "PYTTS_VOLUME": "1.0",
            "PYTTS_VOICE_ID": "1",
            "TTS_OUTPUT_FILE": "output",
            "TTS_OUTPUT_FORMAT": "wav"
        }.get(key)

        mock_engine = MagicMock()
        mock_voice_0 = MagicMock()
        mock_voice_0.id = "voice-id-0"
        mock_voice_1 = MagicMock()
        mock_voice_1.id = "voice-id-1"
        mock_engine.getProperty.return_value = [mock_voice_0, mock_voice_1]
        mock_pyttsx3_init.return_value = mock_engine

        service = pytts_module.PyTTSService()

        mock_engine.setProperty.assert_any_call("voice", "voice-id-1")


class TestGetPyTTSService:

    def setup_method(self):
        """Reset the singleton before each test."""
        pytts_module.pytts_service = None

    @patch("app.tts.pytts.pyttsx3.init")
    @patch("app.tts.pytts.os.getenv")
    def test_get_pytts_service_creates_instance(self, mock_getenv, mock_pyttsx3_init):
        """Test that get_pytts_service creates a new PyTTSService instance."""
        mock_getenv.side_effect = lambda key: {
            "PYTTS_VOICE_RATE": "150",
            "PYTTS_VOLUME": "0.9",
            "PYTTS_VOICE_ID": "0",
            "TTS_OUTPUT_FILE": "test_output",
            "TTS_OUTPUT_FORMAT": "mp3"
        }.get(key)

        mock_engine = MagicMock()
        mock_voice = MagicMock()
        mock_voice.id = "voice-id-0"
        mock_engine.getProperty.return_value = [mock_voice]
        mock_pyttsx3_init.return_value = mock_engine

        service = pytts_module.get_pytts_service()

        assert service is not None
        assert isinstance(service, pytts_module.PyTTSService)

    @patch("app.tts.pytts.pyttsx3.init")
    @patch("app.tts.pytts.os.getenv")
    def test_get_pytts_service_returns_singleton(self, mock_getenv, mock_pyttsx3_init):
        """Test that get_pytts_service returns the same instance on subsequent calls."""
        mock_getenv.side_effect = lambda key: {
            "PYTTS_VOICE_RATE": "150",
            "PYTTS_VOLUME": "0.9",
            "PYTTS_VOICE_ID": "0",
            "TTS_OUTPUT_FILE": "test_output",
            "TTS_OUTPUT_FORMAT": "mp3"
        }.get(key)

        mock_engine = MagicMock()
        mock_voice = MagicMock()
        mock_voice.id = "voice-id-0"
        mock_engine.getProperty.return_value = [mock_voice]
        mock_pyttsx3_init.return_value = mock_engine

        service1 = pytts_module.get_pytts_service()
        service2 = pytts_module.get_pytts_service()

        assert service1 is service2
        mock_pyttsx3_init.assert_called_once()

    @patch("app.tts.pytts.pyttsx3.init")
    @patch("app.tts.pytts.os.getenv")
    def test_get_pytts_service_caches_instance(self, mock_getenv, mock_pyttsx3_init):
        """Test that the service is cached in the global variable."""
        mock_getenv.side_effect = lambda key: {
            "PYTTS_VOICE_RATE": "150",
            "PYTTS_VOLUME": "0.9",
            "PYTTS_VOICE_ID": "0",
            "TTS_OUTPUT_FILE": "test_output",
            "TTS_OUTPUT_FORMAT": "mp3"
        }.get(key)

        mock_engine = MagicMock()
        mock_voice = MagicMock()
        mock_voice.id = "voice-id-0"
        mock_engine.getProperty.return_value = [mock_voice]
        mock_pyttsx3_init.return_value = mock_engine

        assert pytts_module.pytts_service is None

        service = pytts_module.get_pytts_service()

        assert pytts_module.pytts_service is service
