import logging

from elevenlabs.client import ElevenLabs

from app.config import get_settings

logger = logging.getLogger(__name__)

elevenlabs_service = None


def get_elevenlabs_service():
    global elevenlabs_service
    if elevenlabs_service is None:
        elevenlabs_service = ElevenLabsService()
    return elevenlabs_service


class ElevenLabsService:

    def __init__(self):
        settings = get_settings()
        self.elevenlabs = ElevenLabs(api_key=settings.elevenlabs_api_key)
        self.voice_id = settings.elevenlabs_voice_id
        self.model_id = settings.elevenlabs_model_id
        self.output_path = settings.tts_output_path

    def text_to_speech(self, text: str):
        logger.info("Generating TTS audio with ElevenLabs")
        text = "Generated by ElevenLabs: " + text
        audio_generator = self.elevenlabs.text_to_speech.convert(
            text=text,
            voice_id=self.voice_id,
            model_id=self.model_id,
        )
        audio_bytes = b"".join(audio_generator)
        with open(self.output_path, "wb") as f:
            f.write(audio_bytes)
