import logging
import pyttsx3

from app.config import get_settings

logger = logging.getLogger(__name__)

pytts_service = None


def get_pytts_service():
    global pytts_service
    if pytts_service is None:
        pytts_service = PyTTSService()
    return pytts_service


class PyTTSService:

    def __init__(self):
        settings = get_settings()
        self.pytts_service = pyttsx3.init()
        self.pytts_service.setProperty("rate", settings.pytts_voice_rate)
        self.pytts_service.setProperty("volume", settings.pytts_volume)
        voices = self.pytts_service.getProperty("voices")
        self.pytts_service.setProperty("voice", voices[int(settings.pytts_voice_id)].id)
        self.output_path = settings.tts_output_path

    def text_to_speech(self, text: str):
        logger.info("Generating TTS audio with PyTTS")
        text = "Generated by PyTTS: " + text
        self.pytts_service.save_to_file(text, self.output_path)
        self.pytts_service.runAndWait()
        self.pytts_service.stop()